[en]
    weight          = 1
    languageCode    = "en"
    languageName    = "English"
    contentDir      = "content/en"
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; Pantry Peers"
    # The title of site
    title           = "Superphysics"

    [en.params]
        author = "Pantry Peers"
        keywords = "Superphysics, Physics, Economics, Metaphysics"
        description = "Superphysics is a New Science Based on Metaphysics and Socratic Dialectics. It enhances the Material, Medical, Social and Economic Sciences"

[tl]
    weight          = 2
    languageCode    = "tl"
    languageName    = "Tagalog"
    contentDir      = "content/tl"
    copyright       = "&copy; Pantry Peers"
    title           = "Superphysics"

    [tl.params]
        author = "Pantry Peers"
        # keywords = "Hugo-Bulma, Hugo, Bulma, 主题"
        description = "Superphysics is a New Science Based on Metaphysics and Socratic Dialectics. It enhances the Material, Medical, Social and Economic Sciences"

[vi]
    weight          = 3
    languageCode    = "vi"
    languageName    = "Vietnamese"
    contentDir      = "content/vi"

    copyright       = "&copy; {year} Pantry Peers"
    title           = "Superphysics"

    [vi.params]
        author = "Pantry Peers"
        # keywords = "Hugo-Bulma, Hugo, Bulma, 主題"
        description = "Superphysics is a New Science Based on Metaphysics and Socratic Dialectics. It enhances the Material, Medical, Social and Economic Sciences"
